require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransactionSharesController do

  # This should return the minimal set of attributes required to create a valid
  # TransactionShare. As you add validations to TransactionShare, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "transaction_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransactionSharesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all transaction_shares as @transaction_shares" do
      transaction_share = TransactionShare.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transaction_shares).should eq([transaction_share])
    end
  end

  describe "GET show" do
    it "assigns the requested transaction_share as @transaction_share" do
      transaction_share = TransactionShare.create! valid_attributes
      get :show, {:id => transaction_share.to_param}, valid_session
      assigns(:transaction_share).should eq(transaction_share)
    end
  end

  describe "GET new" do
    it "assigns a new transaction_share as @transaction_share" do
      get :new, {}, valid_session
      assigns(:transaction_share).should be_a_new(TransactionShare)
    end
  end

  describe "GET edit" do
    it "assigns the requested transaction_share as @transaction_share" do
      transaction_share = TransactionShare.create! valid_attributes
      get :edit, {:id => transaction_share.to_param}, valid_session
      assigns(:transaction_share).should eq(transaction_share)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransactionShare" do
        expect {
          post :create, {:transaction_share => valid_attributes}, valid_session
        }.to change(TransactionShare, :count).by(1)
      end

      it "assigns a newly created transaction_share as @transaction_share" do
        post :create, {:transaction_share => valid_attributes}, valid_session
        assigns(:transaction_share).should be_a(TransactionShare)
        assigns(:transaction_share).should be_persisted
      end

      it "redirects to the created transaction_share" do
        post :create, {:transaction_share => valid_attributes}, valid_session
        response.should redirect_to(TransactionShare.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transaction_share as @transaction_share" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionShare.any_instance.stub(:save).and_return(false)
        post :create, {:transaction_share => { "transaction_id" => "invalid value" }}, valid_session
        assigns(:transaction_share).should be_a_new(TransactionShare)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionShare.any_instance.stub(:save).and_return(false)
        post :create, {:transaction_share => { "transaction_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transaction_share" do
        transaction_share = TransactionShare.create! valid_attributes
        # Assuming there are no other transaction_shares in the database, this
        # specifies that the TransactionShare created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransactionShare.any_instance.should_receive(:update).with({ "transaction_id" => "1" })
        put :update, {:id => transaction_share.to_param, :transaction_share => { "transaction_id" => "1" }}, valid_session
      end

      it "assigns the requested transaction_share as @transaction_share" do
        transaction_share = TransactionShare.create! valid_attributes
        put :update, {:id => transaction_share.to_param, :transaction_share => valid_attributes}, valid_session
        assigns(:transaction_share).should eq(transaction_share)
      end

      it "redirects to the transaction_share" do
        transaction_share = TransactionShare.create! valid_attributes
        put :update, {:id => transaction_share.to_param, :transaction_share => valid_attributes}, valid_session
        response.should redirect_to(transaction_share)
      end
    end

    describe "with invalid params" do
      it "assigns the transaction_share as @transaction_share" do
        transaction_share = TransactionShare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionShare.any_instance.stub(:save).and_return(false)
        put :update, {:id => transaction_share.to_param, :transaction_share => { "transaction_id" => "invalid value" }}, valid_session
        assigns(:transaction_share).should eq(transaction_share)
      end

      it "re-renders the 'edit' template" do
        transaction_share = TransactionShare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionShare.any_instance.stub(:save).and_return(false)
        put :update, {:id => transaction_share.to_param, :transaction_share => { "transaction_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transaction_share" do
      transaction_share = TransactionShare.create! valid_attributes
      expect {
        delete :destroy, {:id => transaction_share.to_param}, valid_session
      }.to change(TransactionShare, :count).by(-1)
    end

    it "redirects to the transaction_shares list" do
      transaction_share = TransactionShare.create! valid_attributes
      delete :destroy, {:id => transaction_share.to_param}, valid_session
      response.should redirect_to(transaction_shares_url)
    end
  end

end
